package com.zhouwei.springboot.mapper;


import com.zhouwei.springboot.entity.SjIpSource;

import java.util.List;

public interface SjIpSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_ip_source
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_ip_source
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insert(SjIpSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_ip_source
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insertSelective(SjIpSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_ip_source
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    SjIpSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_ip_source
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKeySelective(SjIpSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_ip_source
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKey(SjIpSource record);

    /**
     * 查询所有IP源信息
     */
    List findAllIp(Integer id);
}