package com.zhouwei.springboot.mapper;

import com.zhouwei.springboot.entity.SjMethod;

public interface SjMethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_method
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_method
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insert(SjMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_method
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insertSelective(SjMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_method
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    SjMethod selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_method
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKeySelective(SjMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_method
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKey(SjMethod record);
}