package com.zhouwei.springboot.mapper;


import com.zhouwei.springboot.entity.SjQdGetUrl;

import java.util.List;
import java.util.Map;

public interface SjQdGetUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_qd_get_url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_qd_get_url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insert(SjQdGetUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_qd_get_url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insertSelective(SjQdGetUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_qd_get_url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    SjQdGetUrl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_qd_get_url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKeySelective(SjQdGetUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_qd_get_url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKey(SjQdGetUrl record);

    /**
     * 查询任务url
     */
    List findQdUrl(Map map);
}