package com.zhouwei.springboot.mapper;

import com.zhouwei.springboot.entity.SjTaskDetail;

import java.util.List;
import java.util.Map;

public interface SjTaskDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_detail
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_detail
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insert(SjTaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_detail
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insertSelective(SjTaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_detail
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    SjTaskDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_detail
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKeySelective(SjTaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_detail
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKey(SjTaskDetail record);
    /**
     * 删除详情信息byTaskId
     */
    int delSjDetialByTaskId(Integer id);
    /**
     * 查询任务详情
     */
    List findSjDetailMess(Map mp);

    /**
     * 统计任务10分钟量
     */
    List totalMTask(Map mp);
    /**
     * 统计任务小时量
     */
    List totalHTask(Map mp);
    /**
     * 根据关键词Id查询统计
     */
    List findSjDetailGjc(Map mp);
    /**
     * ip排重
     */
    int findIpPc(Map mp);
    /**
     * 删除详情
     */
    int delIdfa(Map mp);
    /**
     * 回调修改信息
     */
    int updateCallBackMess(Map mp);
}