package com.zhouwei.springboot.mapper;


import com.zhouwei.springboot.entity.SjTaskGjcList;

import java.util.List;
import java.util.Map;

public interface SjTaskGjcListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_gjc_list
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_gjc_list
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insert(SjTaskGjcList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_gjc_list
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insertSelective(SjTaskGjcList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_gjc_list
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    SjTaskGjcList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_gjc_list
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKeySelective(SjTaskGjcList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_gjc_list
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKey(SjTaskGjcList record);

    /**
     * 删除任务关键所有词
     */
    int delSjGjcListByTaaskId(Integer id);
    /**
     * 根据任务id查询所有关键词
     */
    List findGjcByTaskId(Map mp);
}