package com.zhouwei.springboot.mapper;

import com.zhouwei.springboot.entity.SjTaskTotal;
import org.apache.catalina.LifecycleState;

import java.util.List;
import java.util.Map;

public interface SjTaskTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_total
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_total
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    int insert(SjTaskTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_total
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    int insertSelective(SjTaskTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_total
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    SjTaskTotal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_total
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    int updateByPrimaryKeySelective(SjTaskTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_total
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    int updateByPrimaryKey(SjTaskTotal record);

    /**
     * 查询统计信息
     */
    List findSjTotal(Map map);
}