package com.zhouwei.springboot.mapper;


import com.zhouwei.springboot.entity.SjTaskIphone;

import java.util.List;
import java.util.Map;

public interface SjTaskIphoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_iphone
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_iphone
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insert(SjTaskIphone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_iphone
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int insertSelective(SjTaskIphone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_iphone
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    SjTaskIphone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_iphone
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKeySelective(SjTaskIphone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_task_iphone
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    int updateByPrimaryKey(SjTaskIphone record);

    /**
     * 查询手机编号信息
     */
    List<SjTaskIphone> findSJIphoneByR2(Map mp);

    /**
     * 全部任务id 为0
     */
    int updateTaskIdAllZero(Integer id);
    /**
     * 查询任务id 根据手机编号
     */
    List<SjTaskIphone> findTaskIdByIphoneNum(Integer iphoneNum);
}