package com.zhouwei.springboot.entity;

import java.util.Date;

public class SjIpSource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.name
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.pass
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.msg
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.states
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer states;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.changTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Date changtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.type
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_ip_source.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.id
     *
     * @return the value of sj_ip_source.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.id
     *
     * @param id the value for sj_ip_source.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.url
     *
     * @return the value of sj_ip_source.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.url
     *
     * @param url the value for sj_ip_source.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.name
     *
     * @return the value of sj_ip_source.name
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.name
     *
     * @param name the value for sj_ip_source.name
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.pass
     *
     * @return the value of sj_ip_source.pass
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.pass
     *
     * @param pass the value for sj_ip_source.pass
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.msg
     *
     * @return the value of sj_ip_source.msg
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.msg
     *
     * @param msg the value for sj_ip_source.msg
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.states
     *
     * @return the value of sj_ip_source.states
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.states
     *
     * @param states the value for sj_ip_source.states
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setStates(Integer states) {
        this.states = states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.changTime
     *
     * @return the value of sj_ip_source.changTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Date getChangtime() {
        return changtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.changTime
     *
     * @param changtime the value for sj_ip_source.changTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setChangtime(Date changtime) {
        this.changtime = changtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.type
     *
     * @return the value of sj_ip_source.type
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.type
     *
     * @param type the value for sj_ip_source.type
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.r1
     *
     * @return the value of sj_ip_source.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR1() {
        return r1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.r1
     *
     * @param r1 the value for sj_ip_source.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR1(String r1) {
        this.r1 = r1 == null ? null : r1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.r2
     *
     * @return the value of sj_ip_source.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR2() {
        return r2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.r2
     *
     * @param r2 the value for sj_ip_source.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR2(String r2) {
        this.r2 = r2 == null ? null : r2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_ip_source.r3
     *
     * @return the value of sj_ip_source.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR3() {
        return r3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_ip_source.r3
     *
     * @param r3 the value for sj_ip_source.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR3(String r3) {
        this.r3 = r3 == null ? null : r3.trim();
    }
}