package com.zhouwei.springboot.entity;

public class SjLua {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_lua.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_lua.name
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_lua.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_lua.type
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_lua.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_lua.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_lua.id
     *
     * @return the value of sj_lua.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_lua.id
     *
     * @param id the value for sj_lua.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_lua.name
     *
     * @return the value of sj_lua.name
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_lua.name
     *
     * @param name the value for sj_lua.name
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_lua.url
     *
     * @return the value of sj_lua.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_lua.url
     *
     * @param url the value for sj_lua.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_lua.type
     *
     * @return the value of sj_lua.type
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_lua.type
     *
     * @param type the value for sj_lua.type
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_lua.r1
     *
     * @return the value of sj_lua.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR1() {
        return r1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_lua.r1
     *
     * @param r1 the value for sj_lua.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR1(String r1) {
        this.r1 = r1 == null ? null : r1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_lua.r2
     *
     * @return the value of sj_lua.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR2() {
        return r2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_lua.r2
     *
     * @param r2 the value for sj_lua.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR2(String r2) {
        this.r2 = r2 == null ? null : r2.trim();
    }
}