package com.zhouwei.springboot.entity;

import java.util.Date;

public class SjMethod {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_method.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_method.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_method.method
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_method.changeTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Date changetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_method.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_method.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_method.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_method.r4
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_method.r5
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_method.id
     *
     * @return the value of sj_method.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_method.id
     *
     * @param id the value for sj_method.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_method.url
     *
     * @return the value of sj_method.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_method.url
     *
     * @param url the value for sj_method.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_method.method
     *
     * @return the value of sj_method.method
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_method.method
     *
     * @param method the value for sj_method.method
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_method.changeTime
     *
     * @return the value of sj_method.changeTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Date getChangetime() {
        return changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_method.changeTime
     *
     * @param changetime the value for sj_method.changeTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setChangetime(Date changetime) {
        this.changetime = changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_method.r1
     *
     * @return the value of sj_method.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR1() {
        return r1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_method.r1
     *
     * @param r1 the value for sj_method.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR1(String r1) {
        this.r1 = r1 == null ? null : r1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_method.r2
     *
     * @return the value of sj_method.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR2() {
        return r2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_method.r2
     *
     * @param r2 the value for sj_method.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR2(String r2) {
        this.r2 = r2 == null ? null : r2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_method.r3
     *
     * @return the value of sj_method.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR3() {
        return r3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_method.r3
     *
     * @param r3 the value for sj_method.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR3(String r3) {
        this.r3 = r3 == null ? null : r3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_method.r4
     *
     * @return the value of sj_method.r4
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR4() {
        return r4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_method.r4
     *
     * @param r4 the value for sj_method.r4
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR4(String r4) {
        this.r4 = r4 == null ? null : r4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_method.r5
     *
     * @return the value of sj_method.r5
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR5() {
        return r5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_method.r5
     *
     * @param r5 the value for sj_method.r5
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR5(String r5) {
        this.r5 = r5 == null ? null : r5.trim();
    }
}