package com.zhouwei.springboot.entity;

import java.util.Date;

public class SjQdGetUrl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.qtype
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer qtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.ttype
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer ttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.backmess
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String backmess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.taskId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.changTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Date changtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_qd_get_url.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.id
     *
     * @return the value of sj_qd_get_url.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.id
     *
     * @param id the value for sj_qd_get_url.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.qtype
     *
     * @return the value of sj_qd_get_url.qtype
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getQtype() {
        return qtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.qtype
     *
     * @param qtype the value for sj_qd_get_url.qtype
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setQtype(Integer qtype) {
        this.qtype = qtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.ttype
     *
     * @return the value of sj_qd_get_url.ttype
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getTtype() {
        return ttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.ttype
     *
     * @param ttype the value for sj_qd_get_url.ttype
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setTtype(Integer ttype) {
        this.ttype = ttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.url
     *
     * @return the value of sj_qd_get_url.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.url
     *
     * @param url the value for sj_qd_get_url.url
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.backmess
     *
     * @return the value of sj_qd_get_url.backmess
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getBackmess() {
        return backmess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.backmess
     *
     * @param backmess the value for sj_qd_get_url.backmess
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setBackmess(String backmess) {
        this.backmess = backmess == null ? null : backmess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.taskId
     *
     * @return the value of sj_qd_get_url.taskId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.taskId
     *
     * @param taskid the value for sj_qd_get_url.taskId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.changTime
     *
     * @return the value of sj_qd_get_url.changTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Date getChangtime() {
        return changtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.changTime
     *
     * @param changtime the value for sj_qd_get_url.changTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setChangtime(Date changtime) {
        this.changtime = changtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.r1
     *
     * @return the value of sj_qd_get_url.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR1() {
        return r1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.r1
     *
     * @param r1 the value for sj_qd_get_url.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR1(String r1) {
        this.r1 = r1 == null ? null : r1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.r2
     *
     * @return the value of sj_qd_get_url.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR2() {
        return r2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.r2
     *
     * @param r2 the value for sj_qd_get_url.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR2(String r2) {
        this.r2 = r2 == null ? null : r2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_qd_get_url.r3
     *
     * @return the value of sj_qd_get_url.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR3() {
        return r3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_qd_get_url.r3
     *
     * @param r3 the value for sj_qd_get_url.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR3(String r3) {
        this.r3 = r3 == null ? null : r3.trim();
    }
}