package com.zhouwei.springboot.entity;

import lombok.Data;

import java.util.Date;

@Data
public class SjTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.bundleId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String bundleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.names
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String names;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.gjc
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String gjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.qd
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String qd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.number
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.sjnumber
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer sjnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.taskTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer tasktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.appstoreId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String appstoreid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.changeTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Date changetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.cusId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.cusMess
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String cusmess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.type
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.taskType
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer tasktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.clicks
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer clicks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.points
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.appurl
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String appurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.isEnd
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer isend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.r4
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.r5
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.r6
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task.r7
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r7;


}