package com.zhouwei.springboot.entity;

import java.util.Date;

public class SjTaskTotal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.id
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.bundleId
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String bundleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.names
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String names;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.gjc
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String gjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.qd
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String qd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.number
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.sjnumber
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private Integer sjnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.taskTime
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private Integer tasktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.appstoreId
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String appstoreid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.changeTime
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private Date changetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.cusId
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.cusMess
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String cusmess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.type
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.taskType
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private Integer tasktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.clicks
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private Integer clicks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.points
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.appurl
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String appurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.isEnd
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private Integer isend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.r1
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String r1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.r2
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String r2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.r3
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String r3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.r4
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String r4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.r5
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String r5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.r6
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String r6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_total.r7
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    private String r7;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.id
     *
     * @return the value of sj_task_total.id
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.id
     *
     * @param id the value for sj_task_total.id
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.bundleId
     *
     * @return the value of sj_task_total.bundleId
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getBundleid() {
        return bundleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.bundleId
     *
     * @param bundleid the value for sj_task_total.bundleId
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setBundleid(String bundleid) {
        this.bundleid = bundleid == null ? null : bundleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.names
     *
     * @return the value of sj_task_total.names
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getNames() {
        return names;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.names
     *
     * @param names the value for sj_task_total.names
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setNames(String names) {
        this.names = names == null ? null : names.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.gjc
     *
     * @return the value of sj_task_total.gjc
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getGjc() {
        return gjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.gjc
     *
     * @param gjc the value for sj_task_total.gjc
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setGjc(String gjc) {
        this.gjc = gjc == null ? null : gjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.qd
     *
     * @return the value of sj_task_total.qd
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getQd() {
        return qd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.qd
     *
     * @param qd the value for sj_task_total.qd
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setQd(String qd) {
        this.qd = qd == null ? null : qd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.number
     *
     * @return the value of sj_task_total.number
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.number
     *
     * @param number the value for sj_task_total.number
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.sjnumber
     *
     * @return the value of sj_task_total.sjnumber
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public Integer getSjnumber() {
        return sjnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.sjnumber
     *
     * @param sjnumber the value for sj_task_total.sjnumber
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setSjnumber(Integer sjnumber) {
        this.sjnumber = sjnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.taskTime
     *
     * @return the value of sj_task_total.taskTime
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public Integer getTasktime() {
        return tasktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.taskTime
     *
     * @param tasktime the value for sj_task_total.taskTime
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setTasktime(Integer tasktime) {
        this.tasktime = tasktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.appstoreId
     *
     * @return the value of sj_task_total.appstoreId
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getAppstoreid() {
        return appstoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.appstoreId
     *
     * @param appstoreid the value for sj_task_total.appstoreId
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setAppstoreid(String appstoreid) {
        this.appstoreid = appstoreid == null ? null : appstoreid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.changeTime
     *
     * @return the value of sj_task_total.changeTime
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public Date getChangetime() {
        return changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.changeTime
     *
     * @param changetime the value for sj_task_total.changeTime
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setChangetime(Date changetime) {
        this.changetime = changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.cusId
     *
     * @return the value of sj_task_total.cusId
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.cusId
     *
     * @param cusid the value for sj_task_total.cusId
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setCusid(String cusid) {
        this.cusid = cusid == null ? null : cusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.cusMess
     *
     * @return the value of sj_task_total.cusMess
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getCusmess() {
        return cusmess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.cusMess
     *
     * @param cusmess the value for sj_task_total.cusMess
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setCusmess(String cusmess) {
        this.cusmess = cusmess == null ? null : cusmess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.type
     *
     * @return the value of sj_task_total.type
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.type
     *
     * @param type the value for sj_task_total.type
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.taskType
     *
     * @return the value of sj_task_total.taskType
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public Integer getTasktype() {
        return tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.taskType
     *
     * @param tasktype the value for sj_task_total.taskType
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setTasktype(Integer tasktype) {
        this.tasktype = tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.clicks
     *
     * @return the value of sj_task_total.clicks
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public Integer getClicks() {
        return clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.clicks
     *
     * @param clicks the value for sj_task_total.clicks
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.points
     *
     * @return the value of sj_task_total.points
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.points
     *
     * @param points the value for sj_task_total.points
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setPoints(String points) {
        this.points = points == null ? null : points.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.appurl
     *
     * @return the value of sj_task_total.appurl
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getAppurl() {
        return appurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.appurl
     *
     * @param appurl the value for sj_task_total.appurl
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setAppurl(String appurl) {
        this.appurl = appurl == null ? null : appurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.isEnd
     *
     * @return the value of sj_task_total.isEnd
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.isEnd
     *
     * @param isend the value for sj_task_total.isEnd
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.r1
     *
     * @return the value of sj_task_total.r1
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getR1() {
        return r1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.r1
     *
     * @param r1 the value for sj_task_total.r1
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setR1(String r1) {
        this.r1 = r1 == null ? null : r1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.r2
     *
     * @return the value of sj_task_total.r2
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getR2() {
        return r2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.r2
     *
     * @param r2 the value for sj_task_total.r2
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setR2(String r2) {
        this.r2 = r2 == null ? null : r2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.r3
     *
     * @return the value of sj_task_total.r3
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getR3() {
        return r3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.r3
     *
     * @param r3 the value for sj_task_total.r3
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setR3(String r3) {
        this.r3 = r3 == null ? null : r3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.r4
     *
     * @return the value of sj_task_total.r4
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getR4() {
        return r4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.r4
     *
     * @param r4 the value for sj_task_total.r4
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setR4(String r4) {
        this.r4 = r4 == null ? null : r4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.r5
     *
     * @return the value of sj_task_total.r5
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getR5() {
        return r5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.r5
     *
     * @param r5 the value for sj_task_total.r5
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setR5(String r5) {
        this.r5 = r5 == null ? null : r5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.r6
     *
     * @return the value of sj_task_total.r6
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getR6() {
        return r6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.r6
     *
     * @param r6 the value for sj_task_total.r6
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setR6(String r6) {
        this.r6 = r6 == null ? null : r6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_total.r7
     *
     * @return the value of sj_task_total.r7
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public String getR7() {
        return r7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_total.r7
     *
     * @param r7 the value for sj_task_total.r7
     *
     * @mbggenerated Tue Apr 07 13:28:48 CST 2020
     */
    public void setR7(String r7) {
        this.r7 = r7 == null ? null : r7.trim();
    }
}