package com.zhouwei.springboot.entity;

public class SjTaskDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.idfa
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String idfa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.changTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String changtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.ip
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.bundleId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String bundleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.names
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String names;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.appStoreId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String appstoreid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.cusId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.model
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.oss
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String oss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.taskId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.callbacktime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String callbacktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.r4
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.r5
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_detail.r6
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.id
     *
     * @return the value of sj_task_detail.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.id
     *
     * @param id the value for sj_task_detail.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.idfa
     *
     * @return the value of sj_task_detail.idfa
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getIdfa() {
        return idfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.idfa
     *
     * @param idfa the value for sj_task_detail.idfa
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setIdfa(String idfa) {
        this.idfa = idfa == null ? null : idfa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.changTime
     *
     * @return the value of sj_task_detail.changTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getChangtime() {
        return changtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.changTime
     *
     * @param changtime the value for sj_task_detail.changTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setChangtime(String changtime) {
        this.changtime = changtime == null ? null : changtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.ip
     *
     * @return the value of sj_task_detail.ip
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.ip
     *
     * @param ip the value for sj_task_detail.ip
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.bundleId
     *
     * @return the value of sj_task_detail.bundleId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getBundleid() {
        return bundleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.bundleId
     *
     * @param bundleid the value for sj_task_detail.bundleId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setBundleid(String bundleid) {
        this.bundleid = bundleid == null ? null : bundleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.names
     *
     * @return the value of sj_task_detail.names
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getNames() {
        return names;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.names
     *
     * @param names the value for sj_task_detail.names
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setNames(String names) {
        this.names = names == null ? null : names.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.appStoreId
     *
     * @return the value of sj_task_detail.appStoreId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getAppstoreid() {
        return appstoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.appStoreId
     *
     * @param appstoreid the value for sj_task_detail.appStoreId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setAppstoreid(String appstoreid) {
        this.appstoreid = appstoreid == null ? null : appstoreid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.cusId
     *
     * @return the value of sj_task_detail.cusId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.cusId
     *
     * @param cusid the value for sj_task_detail.cusId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setCusid(String cusid) {
        this.cusid = cusid == null ? null : cusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.model
     *
     * @return the value of sj_task_detail.model
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.model
     *
     * @param model the value for sj_task_detail.model
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.oss
     *
     * @return the value of sj_task_detail.oss
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getOss() {
        return oss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.oss
     *
     * @param oss the value for sj_task_detail.oss
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setOss(String oss) {
        this.oss = oss == null ? null : oss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.taskId
     *
     * @return the value of sj_task_detail.taskId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.taskId
     *
     * @param taskid the value for sj_task_detail.taskId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.r1
     *
     * @return the value of sj_task_detail.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR1() {
        return r1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.r1
     *
     * @param r1 the value for sj_task_detail.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR1(String r1) {
        this.r1 = r1 == null ? null : r1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.r2
     *
     * @return the value of sj_task_detail.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR2() {
        return r2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.r2
     *
     * @param r2 the value for sj_task_detail.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR2(String r2) {
        this.r2 = r2 == null ? null : r2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.callbacktime
     *
     * @return the value of sj_task_detail.callbacktime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getCallbacktime() {
        return callbacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.callbacktime
     *
     * @param callbacktime the value for sj_task_detail.callbacktime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setCallbacktime(String callbacktime) {
        this.callbacktime = callbacktime == null ? null : callbacktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.r3
     *
     * @return the value of sj_task_detail.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR3() {
        return r3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.r3
     *
     * @param r3 the value for sj_task_detail.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR3(String r3) {
        this.r3 = r3 == null ? null : r3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.r4
     *
     * @return the value of sj_task_detail.r4
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR4() {
        return r4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.r4
     *
     * @param r4 the value for sj_task_detail.r4
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR4(String r4) {
        this.r4 = r4 == null ? null : r4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.r5
     *
     * @return the value of sj_task_detail.r5
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR5() {
        return r5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.r5
     *
     * @param r5 the value for sj_task_detail.r5
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR5(String r5) {
        this.r5 = r5 == null ? null : r5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_detail.r6
     *
     * @return the value of sj_task_detail.r6
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR6() {
        return r6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_detail.r6
     *
     * @param r6 the value for sj_task_detail.r6
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR6(String r6) {
        this.r6 = r6 == null ? null : r6.trim();
    }

    public SjTaskDetail() {
    }

    public SjTaskDetail(String r3, String r5) {

        this.r3 = r3;
        this.r5 = r5;

    }
}