package com.zhouwei.springboot.entity;

public class SjTaskIphone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_iphone.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_iphone.iphoneNumber
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private Integer iphonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_iphone.taskId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_iphone.changeTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String changetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_iphone.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_iphone.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sj_task_iphone.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    private String r3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_iphone.id
     *
     * @return the value of sj_task_iphone.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_iphone.id
     *
     * @param id the value for sj_task_iphone.id
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_iphone.iphoneNumber
     *
     * @return the value of sj_task_iphone.iphoneNumber
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public Integer getIphonenumber() {
        return iphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_iphone.iphoneNumber
     *
     * @param iphonenumber the value for sj_task_iphone.iphoneNumber
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setIphonenumber(Integer iphonenumber) {
        this.iphonenumber = iphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_iphone.taskId
     *
     * @return the value of sj_task_iphone.taskId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_iphone.taskId
     *
     * @param taskid the value for sj_task_iphone.taskId
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_iphone.changeTime
     *
     * @return the value of sj_task_iphone.changeTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getChangetime() {
        return changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_iphone.changeTime
     *
     * @param changetime the value for sj_task_iphone.changeTime
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setChangetime(String changetime) {
        this.changetime = changetime == null ? null : changetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_iphone.r1
     *
     * @return the value of sj_task_iphone.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR1() {
        return r1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_iphone.r1
     *
     * @param r1 the value for sj_task_iphone.r1
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR1(String r1) {
        this.r1 = r1 == null ? null : r1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_iphone.r2
     *
     * @return the value of sj_task_iphone.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR2() {
        return r2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_iphone.r2
     *
     * @param r2 the value for sj_task_iphone.r2
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR2(String r2) {
        this.r2 = r2 == null ? null : r2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_task_iphone.r3
     *
     * @return the value of sj_task_iphone.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public String getR3() {
        return r3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_task_iphone.r3
     *
     * @param r3 the value for sj_task_iphone.r3
     *
     * @mbggenerated Tue Mar 24 14:55:14 CST 2020
     */
    public void setR3(String r3) {
        this.r3 = r3 == null ? null : r3.trim();
    }
}